name: CI & Release

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies
      run: npm install --verbose
    - name: Run tests
      run: npm test
    - name: Build & Minify
      run: |
        npm run build
        npm run minify
    - name: Verify dist files
      run: |
        echo "Contents of dist folder:"
        ls -la dist/
        echo "Checking for required files:"
        test -f dist/formulae.cjs.js && echo "✓ formulae.cjs.js exists" || echo "✗ formulae.cjs.js missing"
        test -f dist/formulae.esm.js && echo "✓ formulae.esm.js exists" || echo "✗ formulae.esm.js missing"
        test -f dist/formulae.min.js && echo "✓ formulae.min.js exists" || echo "✗ formulae.min.js missing"
    - name: Upload dist artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  release:
    name: Release & Publish to npm
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
    - name: Download dist artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Install production dependencies
      run: npm install --production
    - name: Publish to npm
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npm publish --access public
